### ISSUE TITLE
Addon File Exported to Addon Directory but not found in game

### ISSUE THREAD

**Issue by ramsowo** [hurtonypeter/altmanager2#2]
![image](https://user-images.githubusercontent.com/103061771/161804019-354b67b9-e50e-4f44-b424-86820cdc5b27.png)
![image](https://user-images.githubusercontent.com/103061771/161804195-7b5fb2fa-1ff7-488d-bff0-586e0b59c9a7.png)
![image](https://user-images.githubusercontent.com/103061771/161804229-45faca1c-ec7f-4262-8c81-fb9ad089c5d2.png)

As seen in image, the in game does not find the addon but it is discovered by WoWUp Client and is correctly in directory. Perhaps if installed incorrectly (exported downloaded zip files to Addons folder) then we need readme to correct steps?

**Comment by hurtonypeter** [comment]
Can you try to rename that "altmanager2-master" folder to "AltManager2"?
And also make sure that the AltManager2.lua and AltManager2.toc is right away in that folder, not somewhere deeper, nested.

TBH, this should be installed through curseforge, downloading the zip isn't really the right way to install it, but currently the curseforge made it unavailable...

**Comment by ramsowo** [comment]
Changing that folder name worked! 
![image](https://user-images.githubusercontent.com/103061771/161870302-092751f2-0a02-4f73-931c-831f26487ed8.png)

**Comment by hurtonypeter** [comment]
Awesome, maybe I'll do a release pipeline here in github so the download folder name isn't the repo's name.

**Comment by ramsowo** [comment]
Yeah saw the drama on curse forge, figured since youre kind enough to
update this for us I'd at least contribute any issues I found with your git
repo <3 TY btw, this addon was so much better than the rest for its
simplicity.
