### ISSUE TITLE
Taz'avesh Dungeons not Labeling correctly

### ISSUE THREAD

**Issue by ramsowo** [hurtonypeter/altmanager2#4]
![image](https://user-images.githubusercontent.com/103061771/162636970-262f1c43-9dab-4e28-b12c-9558a3375a1c.png)
I believe that these dungeons are mislabeling because of some text in the local dungeons needs to be added but not a coder so not entirely sure. I adjusted my own notepad file and it seems to fix the missing label.

[391] = "STRT",
[392] = "GMBT",

**Comment by hurtonypeter** [comment]
Mmm this was really fun to confirm.... :D TIL, these are MapChallangeModeID-s, which are "enchanted" on the generic keystone item.

Fixed in 1.0.5.
